apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod-new
  namespace: nilesh
  labels:
    env: dev
    user: nilesh
spec:
  containers:
  - name: c1
    image: mysql
    envFrom:
    - configMapRef:
        name: cm1