apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod-new1
  namespace: nilesh
  labels:
    env: dev
    user: nilesh
spec:
  containers:
  - name: c1
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: cm2
          key: root-pass
    - name: MYSQL_DATABASE
      valueFrom:
        configMapKeyRef:
          name: cm2
          key: sql-db