apiVersion: v1
kind: Service
metadata:
  name: canary-lb
  namespace: nilesh
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
  - port: 80  #service port inside cluster
    targetPort: 80 #container port
    #nodePort: 30020