apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-new
  namespace: nilesh
  annotations:
    kubernetes.io/change-cause: "image tag updating to caddynline-perl for nginx"
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: c1
        image: nginx