apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nilesh
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 80  #service port inside cluster
    targetPort: 80 #container port
